import type { NextPage } from "next";
import Head from "next/head";
import { IHeart, ILogo, IPlus, ISearch, IUser } from "@components/icons";
import s from "../styles/DesignSystem.module.css";

const DesignSystem: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Design System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`flow ${s.main}`}>
        <h1 className="ff-32 fw-medium">Design System</h1>

        <section className="flow my-300">
          <h2 className="ff-24 uppercase">
            <span>01</span> Colors
          </h2>

          <div className={`grid ${s.colors}`}>
            <article>
              <div className="bg-white"></div>
              <h3 className="fs-16 fw-medium my-50">--clr-white</h3>
              <div
                className="grid"
                style={{ gridTemplateColumns: "min-content 1fr" }}
              >
                <p className="uppercase">hsl</p>
                <p style={{ textAlign: "end" }}>53°, 28%, 95%</p>
              </div>
            </article>
            <article>
              <div className="bg-primary"></div>
              <h3 className="fs-16 fw-medium my-50">--clr-primary</h3>
              <div
                className="grid"
                style={{ gridTemplateColumns: "min-content 1fr" }}
              >
                <p className="uppercase">hsl</p>
                <p style={{ textAlign: "end" }}>53°, 28%, 95%</p>
              </div>
            </article>
            <article>
              <div className="bg-secondary"></div>
              <h3 className="fs-16 fw-medium my-50">--clr-secondary</h3>
              <div
                className="grid"
                style={{ gridTemplateColumns: "min-content 1fr" }}
              >
                <p className="uppercase">hsl</p>
                <p style={{ textAlign: "end" }}>53°, 28%, 95%</p>
              </div>
            </article>
          </div>
        </section>

        <section className="flow my-300">
          <h2 className="ff-24 uppercase">
            <span>02</span> Typography
          </h2>

          <div className="flow">
            <article>
              <p className="fs-14 fw-light text-grey">
                BRANDING - HEARO - PLASTER - 126PX
              </p>
              <p className="fs-126 ff-branding text-accent uppercase">fika</p>
            </article>

            <article>
              <p className="fs-14 fw-light text-grey">
                BRANDING - HEADER - MOBILE - PLASTER - 32PX
              </p>
              <p className="fs-32 ff-branding text-accent uppercase">fika</p>
            </article>

            <article>
              <p className="fs-14 fw-light text-grey">
                BODY - LARGE - POPPINS - 28PX -MEDIUM
              </p>
              <p className="fs-28 fw-medium">300</p>
            </article>

            <article>
              <p className="fs-14 fw-light text-grey">
                BODY - DEFAULT - POPPINS - 16PX -REGULAR
              </p>
              <p className="fs-16  fw-regular">Search</p>
            </article>

            <article>
              <p className="fs-14 fw-light text-grey">
                SUBHEADER - POPPINS - 16PX - MEDIUM
              </p>
              <p className="fs-16 fw-medium">Add location</p>
            </article>

            <article>
              <p className="fs-14 fw-light text-grey">
                USERNAME - MONTSERRAT - 16PX SEMIBOLD
              </p>
              <p className="ff-montserrat fs-16 fw-semibold">Maria Olivia</p>
            </article>

            <article>
              <p className="fs-14 fw-light text-grey">
                BUTTON - DEFAULT - POPPIS - 18PX - MEDIUM - UPPERCASE -
                RESPONSIVE
              </p>
              <p className="fs-btn fw-medium uppercase">save</p>
            </article>
          </div>
        </section>

        <section className="flow my-300">
          <h2 className="ff-24 uppercase">
            <span>03</span> Interactive Elements
          </h2>

          <div className="flow">
            <article>
              <h3 className="fs-14 fw-light text-grey my-50">
                <span className="text-grey">A. </span>
                Icons
              </h3>
              <div className="flex">
                <ILogo color="icon-primary" />
                <ISearch />
                <IPlus />
                <IHeart />
                <IUser />
              </div>
            </article>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignSystem;
